CREATE TABLE IF NOT EXISTS `sf_student_profile` (
    sf_contact_id VARCHAR(255) PRIMARY KEY,
    uid VARCHAR(255),
    first_name VARCHAR(255),
    middle_name VARCHAR(255),
    last_name VARCHAR(255),
    name_prefix VARCHAR(255),
    name_suffix VARCHAR(255),
    email VARCHAR(255),
    alternate_email VARCHAR(255),
    gender VARCHAR(255),
    country_of_citizenship VARCHAR(255),
    citz_visa VARCHAR(255),
    has_dual_citizenship VARCHAR(255),
    dual_citizenship_country VARCHAR(255),
    ethnicity_1 VARCHAR(255),
    ethnicity_2 VARCHAR(255),
    contact_hispanic INT,
    linkedin_url VARCHAR(255),
    primary_UG_school VARCHAR(255),
    mobile_phone VARCHAR(255),
    home_phone_formatted VARCHAR(255),
    wechat_id VARCHAR(255),
    military_status VARCHAR(255),
    military_branch VARCHAR(255),
    first_generation_students INT
);
