CREATE TABLE IF NOT EXISTS `sf_student_degree` (
    hs_student_id VARCHAR(255),
    sf_contact_id VARCHAR(255),
    program VARCHAR(255),
    program_type VARCHAR(255),
    start_term VARCHAR(255),
    last_registered_term VARCHAR(255),
    graduation_term VARCHAR(255),
    graduation_clearance VARCHAR(255),
    undergraduate_major VARCHAR(255),
    undergraduate_major_2 VARCHAR(255),
    transfer_type VARCHAR(255),
    cohort VARCHAR(255),
    campus VARCHAR(255),
    level_of_study VARCHAR(255),
    quest_program VARCHAR(255),
    four_plus_one_grad_program VARCHAR(255),
    shady_grove_ind INT,
	contact_company VARCHAR(255),
    contact_title VARCHAR(255),
    months_worked DECIMAL,
    rhs_company_sponsored VARCHAR(255),
    gs_admissions_status VARCHAR(255),
    deposit_fee_transaction_date DATETIME,
    FOREIGN KEY (sf_contact_id) REFERENCES `salesforce_student_profile`(sf_contact_id)
);
